stages:
  - jar
  - image

build_jar:
  stage: jar
  image: maven:latest
  script:
    - mvn clean package

build_image:
  stage: image
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/pqab-ms/service-eureka-server .
    - docker push registry.gitlab.com/pqab-ms/service-eureka-server