stages:
  - jar
  - image

build_jar:
  stage: jar
  image: maven:latest
  artifacts:
    untracked: true
  script:
    - mvn clean package

build_image:
  stage: image
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - jar
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - pwd
    - ls -la
    - docker build -t registry.gitlab.com/pqab-ms/service-eureka-server .
    - docker push registry.gitlab.com/pqab-ms/service-eureka-server
