stages:
  - build_jar
  - build_image

build_jar:
  image: maven:latest
  script:
    - mvn clean package

build_image:
  image: docker:latest
  script:
    - docker build -t registry.gitlab.com/pqab-ms/service-eureka-server .
    - docker push registry.gitlab.com/pqab-ms/service-eureka-server